#!/bin/zsh
#-------------------------------------------------------------------------------
#  Node version management
#-------------------------------------------------------------------------------

# TODO: Questions:
# 1. Make this work silently
check_node_cwd() {
  local node_version="$(node -v | sed 's/^v\(.*\)/\1/')"
  local nvmrc_path="$(cat .nvmrc 2>/dev/null)"
  if [ -n "$nvmrc_path" ]; then
    n auto
  elif [ "$node_version" != "$(n --lts)" ]; then
    n lts_latest
  fi
}

check_node_cwd
