#!/bin/zsh
#-------------------------------------------------------------------------------
#  Node version management
#-------------------------------------------------------------------------------
# pipe the results to /dev/null to silence the output
# but redirect stderr (2) to stdout (1) so we can capture it
# and disown the process using the &| syntax for zsh
# see: https://unix.stackexchange.com/a/240296
local node_version="$(node -v | sed 's/^v\(.*\)/\1/')"
local nvmrc_path="$(cat .nvmrc 2>/dev/null)"
if [ -n "$nvmrc_path" ]; then
  n auto >/dev/null 2>&1 &|
elif [ "$node_version" != "$(n --lts)" ]; then
  n lts_latest >/dev/null 2>&1 &|
fi
