#!/bin/zsh
#-------------------------------------------------------------------------------
#  PLUGIN MANAGEMENT
#-------------------------------------------------------------------------------
ZSH_PLUGIN_DIR="$DOTFILES/.config/zsh/plugins"

zsh_add_file() {
  [ -f "$ZDOTDIR/$1" ] && source "$ZDOTDIR/$1"
}

zsh_source_plugin () {
  zsh_add_file "plugins/$1.zsh"
}

PLUGIN_NAME=$(echo $1 | cut -d "/" -f 2)
if [ -d "$ZDOTDIR/plugins/$PLUGIN_NAME" ]; then
  zsh_add_file "plugins/$PLUGIN_NAME/$PLUGIN_NAME.plugin.zsh" || \
  zsh_add_file "plugins/$PLUGIN_NAME/$PLUGIN_NAME.zsh" || \
  zsh_add_file "plugins/$PLUGIN_NAME/$2.zsh"
elif [[ -n ${DOTS_ALLOW_PLUGIN_INSTALL-} ]]; then
  # Opt-in because this clones over SSH, and on a host with no GitHub key it
  # would stall every new shell until git gave up.
  cd $DOTFILES
  git submodule add "git@github.com:$1.git" "$ZSH_PLUGIN_DIR/$PLUGIN_NAME"
  cd -
else
  print -u2 "zsh_add_plugin: $PLUGIN_NAME is not installed; run 'git submodule update --init --recursive' in \$DOTFILES"
fi
