highlight link NeogitDiffAdd DiffAdd
highlight link NeogitDiffDelete DiffDelete
highlight link NeogitDiffAddHighlight DiffAdd
highlight link NeogitDiffDeleteHighlight DiffDelete
highlight link NeogitDiffContextHighlight ColorColumn
highlight link NeogitHunkHeader TabLine
highlight link NeogitHunkHeaderHighlight DiffText
