highlight NeogitDiffAdd guifg=LightGray guibg=DarkGreen
highlight NeogitDiffDelete guifg=DarkGray guibg=DarkRed
highlight NeogitDiffAddHighlight guifg=LightGray guibg=DarkGreen
highlight NeogitDiffDeleteHighlight guifg=DarkGray guibg=DarkRed
highlight link NeogitDiffContextHighlight CursorLine
highlight link NeogitHunkHeader TabLine
highlight link NeogitHunkHeaderHighlight DiffText
