#!/usr/bin/zsh
#=======================================================================
#       ENV VARIABLES
#=======================================================================
export DOTFILES=$HOME/.dotfiles

if which yarn >/dev/null; then
  export PATH="$PATH:$(yarn global bin)"
fi

export PATH="/usr/local/bin:$PATH"
export PATH="$HOME/.npm/bin:$PATH"

if [[ "$OSTYPE" == "linux-gnu" ]]; then
  # JAVA ==========================================================
  # export JAVA_HOME=/usr/lib/jvm/java-1.11.0-openjdk-amd64
  # Use Java 8 because
  # https://stackoverflow.com/questions/49758849/flutter-io-android-license-status-unknown
  export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
  export PATH=$JAVA_HOME/bin:$PATH
  # GO ============================================================
  export GOPATH=$(go env GOPATH)
  export PATH=$PATH:/usr/local/go/bin
  export PATH=$PATH:$(go env GOPATH)/bin
  # ===============================================================
  export PATH=$HOME/.local/bin:$PATH
  # RUST ==========================================================
  export PATH="$HOME/.cargo/bin:$PATH"
elif [[ "$OSTYPE" == "darwin"* ]]; then
  # FLUTTER =======================================================
  export PATH="$PATH:$HOME/flutter/bin"
  export PATH="$PATH:$HOME/flutter/.pub-cache/bin"
  # Don't try to control go variables on systems we don't have total control over
  if [[ $MINIMAL != true ]]; then
    # Mac OSX
    export GOPATH=$HOME/Desktop/Coding/Go
    export GOROOT=/usr/local/opt/go/libexec
    export PATH=$PATH:/usr/local/opt/go/libexec/bin
    export PATH=$PATH:$(go env GOPATH)/bin
  fi
fi

if [ -d "$HOME/bin" ] ; then
  PATH="$HOME/bin:$PATH"
fi

export MANPATH="/usr/local/man:$MANPATH"

# you may need to manually set your language environment
export LC_ALL=en_GB.UTF-8
export LANG=en_GB.UTF-8

# preferred editor for local and remote sessions
if [ -n "$NVIM_LISTEN_ADDRESS" ]; then
    export VISUAL="nvr -cc split --remote-wait +'set bufhidden=wipe'"
    export EDITOR="nvr -cc split --remote-wait +'set bufhidden=wipe'"
else
    export VISUAL="nvim"
    export EDITOR="nvim"
fi

export USE_EDITOR=$EDITOR

if [ -f "$HOME/.environment.secret.sh" ]; then
  source $HOME/.environment.secret.sh
fi
# ssh
export SSH_KEY_PATH="~/.ssh/rsa_id"

export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=241'

if ! type "$bat" > /dev/null; then
  export BAT_THEME="TwoDark"
fi

# By specifying a path this means ripgrep will check this
# config file and use the arguments within it when it begins a search
export RIPGREP_CONFIG_PATH="$DOTFILES/.config/.rgconfig"

# Setting ag as the default source for fzf

# --files: List files that would be searched but do not search
# --no-ignore: Do not respect .gitignore, etc...
# --hidden: Search hidden files and folders
# --follow: Follow symlinks
# --glob: Additional conditions for search (in this case ignore everything in the .git/ folder)
# Need to escape the "!" and "*" characters using /
# --no-ignore = this flag shows node modules etc
export FZF_DEFAULT_COMMAND='rg --files --no-ignore-vcs --hidden'
# Reference: Man fzf - bind previous and next history commands explicitly or they will swallow up c-n and c-p
export FZF_DEFAULT_OPTS="--history=$HOME/.fzf_history --bind=up:previous-history,down:next-history,ctrl-n:down,ctrl-p:up"

# To apply to the command to CTRL-T as well
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_TMUX=1
