#!/usr/bin/zsh
#=======================================================================
#       ENV VARIABLES
#=======================================================================
export DOTFILES=$HOME/.dotfiles
export PROJECTS_DIR=$HOME/Desktop/projects
export PERSONAL_PROJECTS_DIR=$PROJECTS_DIR/personal

if which yarn >/dev/null; then
  path+=("$(yarn global bin)")
fi

path+=(
  "/usr/local/bin"
  "$HOME/.npm/bin"
)

if [[ "$OSTYPE" == "linux-gnu" ]]; then
  # JAVA ==========================================================
  # export JAVA_HOME=/usr/lib/jvm/java-1.11.0-openjdk-amd64
  # Use Java 8 because -> https://stackoverflow.com/a/49759126
  # add locally built nvim to path, remove this once snaps are working
  # "$HOME/neovim/bin"
  export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
  export GOPATH=$(go env GOPATH)
  path+=(
    "$LUA_PATH"
    "$LUA_CPATH"
    "$JAVA_HOME/bin"
    # Dart ============================================================
    "/usr/lib/dart/bin"
    "$HOME/.pub-cache/bin"
    # GO ============================================================
    "/usr/local/go/bin"
    "$(go env GOPATH)/bin"
    "$HOME/.local/bin"
    # RUST ==========================================================
    "$HOME/.cargo/bin"
  )
elif [[ "$OSTYPE" == "darwin"* ]]; then
  # FLUTTER =======================================================
  path+=(
    "$HOME/flutter/bin"
    "$HOME/flutter/.pub-cache/bin"
  )
  # Don't try to control go variables on systems we don't have total control over
  if [[ $MINIMAL != true ]]; then
    # Mac OSX
    export GOPATH=$HOME/Desktop/Coding/Go
    export GOROOT=/usr/local/opt/go/libexec
    path+=(
      "/usr/local/opt/go/libexec/bin"
      "$(go env GOPATH)/bin"
    )
  fi
fi

if [ -d "$HOME/bin" ] ; then
  path+=("$HOME/bin")
fi

export MANPATH="/usr/local/man:$MANPATH"

# you may need to manually set your language environment
export LC_ALL=en_GB.UTF-8
export LANG=en_GB.UTF-8

# preferred editor for local and remote sessions
if [ -n "$NVIM_LISTEN_ADDRESS" ]; then
    export VISUAL="nvr -cc split --remote-wait +'set bufhidden=wipe'"
    export EDITOR="nvr -cc split --remote-wait +'set bufhidden=wipe'"
else
    export VISUAL="nvim"
    export EDITOR="nvim"
fi

export USE_EDITOR=$EDITOR

if [ -f "$HOME/.environment.secret.sh" ]; then
  source $HOME/.environment.secret.sh
fi
# ssh
export SSH_KEY_PATH="~/.ssh/rsa_id"

export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=241'

if ! type "$bat" > /dev/null; then
  export BAT_THEME="TwoDark"
fi

# Setting ag as the default source for fzf

# --files: List files that would be searched but do not search
# --no-ignore: Do not respect .gitignore, etc...
# --hidden: Search hidden files and folders
# --follow: Follow symlinks
# --glob: Additional conditions for search (in this case ignore everything in the .git/ folder)
# Need to escape the "!" and "*" characters using /
# --no-ignore = this flag shows node modules etc
export FZF_DEFAULT_COMMAND='rg --files --no-ignore-vcs --hidden'
export FZF_DEFAULT_OPTS="--history=$HOME/.fzf_history"

# To apply to the command to CTRL-T as well
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
# Don't open FZF in a separate split in tmux
export FZF_TMUX=0
